### ISSUE TITLE
python errors

### ISSUE THREAD

**Issue by muralikodali** [Bluewind/fb#1]
when i launched fb program , output looks as below:

Traceback (most recent call last):
  File "/usr/local/bin/fb", line 13, in <module>
    import lzma
  File "/home/xxxx/.pyenv/versions/3.6.0/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

**Comment by Bluewind** [comment]
The `lzma` module is a standard module starting with python 3.3. This looks like your python environment has not been set up correctly or some required libraries were not available and lzma support has been disabled (I'm not sure if that is possible though).

The issue seems to be rather common. One example that might help you: https://github.com/pandas-dev/pandas/issues/27532. If it doesn't, I'm sure you can find some more information about this with a quick google search.
